// This adds install and test stages before static code analysis

pipeline {
  agent any

  stages {
    stage('Checkout') {
        steps {
          // Get some code from a GitHub repository
          git branch: 'main', url: 'https://github.com/Baribrahim/OneSky.git'
        }
    }
    stage('Install') {
        steps {
            // Install the ReactJS dependencies
            dir('frontend') {
              sh "npm install"
            }
        }
    }
    // stage('Test') {
    //     steps {
    //       // Run the ReactJS tests
    //       dir('frontend') {
    //         sh 'CI=true npm test -- --run --environment=jsdom'
    //       }
    //     }
    // }
    stage('SonarQube Analysis') {
      environment {
        scannerHome = tool 'sonarqube'
        }
        steps {
            withSonarQubeEnv('sonar-qube-1') {        
              sh "${scannerHome}/bin/sonar-scanner"
        }
        timeout(time: 10, unit: 'MINUTES'){
          waitForQualityGate abortPipeline: true
          }
        }
    }
  }
}