pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        // This checks out the repo at workspace root
        git branch: 'main', url: 'https://github.com/Baribrahim/OneSky.git'
        // After this, your Jenkinsfile (this file) is at: workspace/backend/Jenkinsfile
      }
    }

    stage('Install') {
      steps {
        // We are already in workspace root when the script runs,
        // but this Jenkinsfile lives in backend/, so we need to cd into backend now
        dir('backend') {
          sh '''
            sudo apt-get update -y
            sudo apt-get install -y python3-dev python3-venv pkg-config default-libmysqlclient-dev build-essential

            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          '''
        }
      }
    }

    stage('Test') {
      steps {
        dir('backend') {
          sh '''
            . venv/bin/activate
            pytest --maxfail=1 --disable-warnings -q
          '''
        }
      }
    }

    stage('SonarQube Analysis') {
      environment {
        scannerHome = tool 'sonarqube'
      }
      steps {
        withSonarQubeEnv('sonar-qube-1') {
          // sonar-project.properties is in backend/, so run scanner there
          dir('backend') {
            sh "${scannerHome}/bin/sonar-scanner"
          }
        }

        timeout(time: 10, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

  }
}
