pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Baribrahim/OneSky.git'
      }
    }

    stage('Install') {
      steps {
        dir('backend/functionality') {
          sh '''
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          '''
        }
      }
    }

    stage('Test') {
      steps {
        dir('backend/functionality') {
          withCredentials([file(credentialsId: 'team1-backend-env', variable: 'ENV_FILE')]) {
            sh '''
              set +x
              # Load vars from credential file into current shell
              set -a
              . "$ENV_FILE"
              set +a

              . venv/bin/activate

              # Pass only what pytest needs
              OPENAI_API_KEY="$OPENAI_API_KEY" pytest --cov=. --cov-report=xml --cov-report=term --maxfail=1 --disable-warnings -q
            '''
          }
        }
      }
    }


    stage('SonarQube Analysis') {
      environment {
        scannerHome = tool 'sonarqube'
      }
      steps {
        withSonarQubeEnv('sonar-qube-1') {
          dir('backend') {
            sh "${scannerHome}/bin/sonar-scanner"
          }
        }

        timeout(time: 10, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

  }
}
